### ISSUE TITLE
你能说一下你这个mpc是怎么做的吗？用你这个方法在实物或者仿真的演示视频有吗？

### ISSUE THREAD

**Issue by rosbing** [Mr-Y-B-L/unitreeMPC_guide#1]
你能说一下你这个mpc是怎么做的吗？用你这个方法在实物或者仿真的演示视频有吗？

**Comment by Mr-Y-B-L** [comment]
具体代码在对角步态的代码中

**Comment by rosbing** [comment]
这个为什么是i+1,不是i-1,当i=0时，有state.mpc_states_d.segment(0, 13)，state.root_euler[2] + state.root_ang_vel_d_world[2] * mpc_dt * (i + 1),这个数据都是下一个状态的了，不是i=0时刻的状态。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mr-Y-B-L/unitreeMPC_guide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月21日(星期三) 下午4:32
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Mr-Y-B-L/unitreeMPC_guide] 你能说一下你这个mpc是怎么做的吗？用你这个方法在实物或者仿真的演示视频有吗？ (Issue #1)





 
具体代码在对角步态的代码中
